language: haxe

sudo: required
dist: trusty

os:
  - linux
  - osx

haxe:
  - "3.4.4"
  - development

branches:
  only:
    - develop

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev hxmake .

script:
  - haxelib run hxmake _
  - hxmake _
  - hxmake test
  - hxmake package-haxelib
