version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  matrix:
    - HAXE_VERSION: "3.4.7"

build: off

branches:
  only:
    - develop
    - declarative

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.2.0 -y
  - cinst haxe --version %HAXE_VERSION% --ignore-dependencies -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"

test_script:
  - haxelib dev hxmake .
  - haxelib run hxmake _
  - hxmake _
  - hxmake test
  - hxmake package-haxelib